INSERT into Produtos(nomeProduto, cor, valorAtacad,valorVarejo,descProduto, codigoProduto, dataProduto,tamanhoMinimo,tamanhoMaximo,tag) 
value('KarateGI Básico Mirim','branco','70.00','89.9','Básico 100% algodão','KBM',now(),2,8,'karate kimono infantil mirin algodão'),
('KarateGI Básico Infantil','branco','90.0','115.6','Básico 100% algodão','KB1',now(),10,40,'karate kimono infantil algodão'),
('KarateGI Básico Adulto','branco','105.0','134.9','Básico 100% algodão','KB2',now(),42,48,'karate kimono aldulto mirin algodão'),
('KarateGI Básico Adulto extra','branco','120.0','154.2','Básico 100% algodão','KB3',now(),50,56,'karate kimono adulto extra mirin algodão'),
('KarateGI MaxiPro Mirim','branco','90.0','115.6','MaxiPro PA 67%algod 33%poliest.','MPKM',now(),2,8,'karate kimono poliester infantil mirin algodão'),
('KarateGI MaxiPro Infantil','branco','115.0','147.7','MaxiPro PA 67%algod 33%poliest.','MPK1',now(),10,40,'karate kimono poliester infantil algodão'),
('KarateGI MaxiPro Adulto','branco','135.0','173.4','MaxiPro PA 67%algod 33%poliest.','MPK2',now(),42,48,'karate kimono adulto poliester algodão'),
('KarateGI MaxiPro Adulto extra','branco','160.0','205.5','MaxiPro PA 67%algod 33%poliest.','MPK3',now(),50,56,'karate kimono adulto extra poliester algodão'),
('KarateGI MaxiPro Mirim','preto','100.0','128.5','MaxiPro Preto - (Kobudo)','KBDM',now(),2,8,'karate kimono infantil mirin'),
('KarateGI MaxiPro Infantil','preto','125.0','160.6','MaxiPro Preto - (Kobudo)','KBD1',now(),10,40,'karate kimono infantil'),
('KarateGI MaxiPro Adulto','preto','150.0','192.7','MaxiPro Preto - (Kobudo)','KBD2',now(),42,48,'karate kimono adulto'),
('KarateGI MaxiPro Adulto extra','preto','185.0','237.7','MaxiPro Preto - (Kobudo)','KBD3',now(),50,56,'karate kimono adulto extra'),
('KarateGI "Europa" Mirim','branco','110.0','141.3','Europa liso e ou canelado (Lona PA 50%alg.50%poliest)','EPAM',now(),2,8,'karate kimono infantil poliester mirin algodão'),
('KarateGI "Europa" Infantil','branco','135.0','173.4','Europa liso e ou canelado (Lona PA 50%alg.50%poliest)','EPA1',now(),10,40,'karate kimono infantil poliester algodão'),
('KarateGI "Europa" Adulto','branco','165.0','212.0','Europa liso e ou canelado (Lona PA 50%alg.50%poliest)','EPA2',now(),42,48,'karate kimono adulto poliester algodão'),
('KarateGI "Europa" Adulto extra','branco','190.0','244.1','Europa liso e ou canelado (Lona PA 50%alg.50%poliest)','EPA3',now(),50,56,'karate kimono adulto poliester extra algodão'),
('KarateGI "Star" Mirim','branco','85.0','109.2','Olimpic Star (PAestrela Branco - 50%algod. 50%poliester)','OPSM',now(),2,8,'karate kimono infantil mirin poliester algodão'),
('KarateGI "Star" Infantil','branco','105.0','134.9','Olimpic Star (PAestrela Branco - 50%algod. 50%poliester)','OPS1',now(),10,40,'karate kimono infantil poliester algodão'),
('KarateGI "Star" Adulto','branco','125.0','160.6','Olimpic Star (PAestrela Branco - 50%algod. 50%poliester)','OPS2',now(),42,48,'karate kimono adulto poliester algodão'),
('KarateGI "Star" Adulto extra','branco','145.0','186.3','Olimpic Star (PAestrela Branco - 50%algod. 50%poliester)','OPS3',now(),50,56,'karate kimono poliester adulto extra algodão'),
('KarateGI "Olimpic" Mirim','branco','85.0','109.2','"OlimpicCanel" (PACnelado Branco-50%algod 50%poliester)','OPCM',now(),2,8,'karate kimono infantil mirin poliester algodão'),
('KarateGI "Olimpic" Infantil','branco','105.0','134.9','"OlimpicCanel" (PACnelado Branco-50%algod 50%poliester)','OPC1',now(),10,40,'karate kimono infantil poliester algodão'),
('KarateGI "Olimpic" Adulto','branco','125.0','160.6','"OlimpicCanel" (PACnelado Branco-50%algod 50%poliester)','OPC2',now(),42,48,'karate kimono adulto poliester algodão'),
('KarateGI "Olimpic" Adulto extra','branco','145.0','186.3','"OlimpicCanel" (PACnelado Branco-50%algod 50%poliester)','OPC3',now(),50,56,'karate kimono poliester adulto extra algodão'),
('KarateGI "Premium" Mirim','branco','168.0','215.8','Premium - indicado para KATA -100% algodão Branco','P10.M',now(),2,8,'karate kimono infantil mirin algodão'),
('KarateGI "Premium" Infantil','branco','210.0','269.8','Premium - indicado para KATA -100% algodão Branco','P10.1',now(),10,40,'karate kimono infantil algodão'),
('KarateGI "Premium" Adulto','branco','250.0','321.1','Premium - indicado para KATA -100% algodão Branco','P10.2',now(),42,48,'karate kimono adulto algodão'),
('KarateGI "Premium" Adulto extra','branco','292.0','375.1','Premium - indicado para KATA -100% algodão Branco','P10.3',now(),50,56,'karate kimono adulto extra algodão'),
('KarateGI Fight Mirim','branco','65.0','83.5','FIGHT microfibra 100% poliester - indicado para Shiai - Branco','ATVM',now(),2,8,'karate kimono infantil mirin algodão'),
('KarateGI Fight Infantil','branco','75.0','96.3','FIGHT microfibra 100% poliester - indicado para Shiai - Branco','ATV1',now(),10,40,'karate kimono infantil algodão'),
('KarateGI Fight Adulto','branco','90.0','115.6','FIGHT microfibra 100% poliester - indicado para Shiai - Branco','ATV2',now(),42,48,'karate kimono adulto algodão'),
('KarateGI Fight Adulto extra','branco','105.0','134.9','FIGHT microfibra 100% poliester - indicado para Shiai - Branco','ATV3',now(),50,56,'karate kimono adulto extra algodão'),
('AikidoGI Básico Mirim','branco','70.00','89.9','Básico 100% algodão','AKBM',now(),2,8,'aikido infantil mirin algodao kimono'),
('AikidoGI Básico Infantil','branco','90.0','115.6','Básico 100% algodão','AKB1',now(),10,40,'aikido infantil algodao kimono'),
('AikidoGI Básico Adulto','branco','105.0','134.9','Básico 100% algodão','AKB2',now(),42,48,'aikido adulto algodao kimono'),
('AikidoGI Básico Adulto extra','branco','120.0','154.2','Básico 100% algodão','AKB3',now(),50,56,'aikido adulto extra algodao kimono'),
('AikidoGI MaxiPro Mirim','branco','90.0','115.6','"MaxiPro" Reforçado branco','MPAM',now(),2,8,'aikido infantil mirim algodao kimono'),
('AikidoGI MaxiPro Infantil','branco','115.0','147.7','"MaxiPro" Reforçado branco','MPA1',now(),10,40,'aikido infantil algodao kimono'),
('AikidoGI MaxiPro Adulto','branco','135.0','173.4','"MaxiPro" Reforçado branco','MPB2',now(),42,48,'aikido adulto algodao kimono'),
('AikidoGI MaxiPro Adulto extra','branco','160.0','205.5','"MaxiPro" Reforçado branco','MPC3',now(),50,56,'aikido adulto extra algodao kimono'),
('AikidoGI Trançadinho Mirim','preto','80.0','102.8','"Trançadinho" Reforçado 100% Algodão Branco','TIAKM',now(),2,8,'trançadinho aikido infantil mirim kobudo algodao kimono'),
('AikidoGI Trançadinho Infantil','preto','95.0','122.6','"Trançadinho" Reforçado 100% Algodão Branco','TIAK1',now(),10,40,'trançadinho aikido infantil kobudo algodao kimono'),
('AikidoGI Trançadinho Adulto','preto','115.0','147.7','"Trançadinho" Reforçado 100% Algodão Branco','TIAK2',now(),42,48,'trançadinho aikido adulto kobudo algodao kimono'),
('AikidoGI Trançadinho Adulto extra','preto','135.0','173.4','"Trançadinho" Reforçado 100% Algodão Branco','TIAK3',now(),50,56,'trançadinho aikido adulto extra kobudo algodao kimono'),
('AikidoGI "Europeu" Mirim','branco','110.0','141.3','Europa liso e ou canelado (Lona PA 50%alg.50%poliest)','EAKM',now(),2,8,'aikido europeu mirim algodao poliester infantil algodao kimono'),
('AikidoGI "Europeu" Infantil','branco','135.0','173.4','Europa liso e ou canelado (Lona PA 50%alg.50%poliest)','EAK1',now(),10,40,'aikido trançadinho infantil algodao algodao poliester kimono'),
('AikidoGI "Europeu" trançadinho Adulto','branco','165.0','212.0','Europa liso e ou canelado (Lona PA 50%alg.50%poliest)','EAK2',now(),42,48,'aikido trançadinho adulto algodao poliester algodao kimono'),
('AikidoGI "Europeu" Adultotrançadinho extra','branco','190.0','244.1','Europa liso e ou canelado (Lona PA 50%alg.50%poliest)','EAK3',now(),50,56,'aikido trançadinho adulto extra algodao poliester algodao kimono'),
('AikidoGI "Canelado" Mirim','branco','110.0','141.3','OlimpicStar (PAestrela Branco - 50%algod. 50%poliester)','OAKM',now(),2,8,'aikido infantil mirim algodao poliester algodao kimono'),
('AikidoGI "Canelado" Infantil','branco','135.0','173.4','OlimpicStar (PAestrela Branco - 50%algod. 50%poliester)','OAK1',now(),10,40,'aikido infantil algodao poliester algodao kimono'),
('AikidoGI "Canelado" Adulto','branco','165.0','212.0','OlimpicStar (PAestrela Branco - 50%algod. 50%poliester)','OAK2',now(),42,48,'aikido adulto algodao poliester algodao kimono'),
('AikidoGI "Canelado" Adulto extra','branco','190.0','244.1','OlimpicStar (PAestrela Branco - 50%algod. 50%poliester)','OPS3',now(),50,56,'aikido adulto extra algodao poliester algodao kimono'),
('AikidoGI "Star" Mirim','branco','85.0','109.0','OlimpicStar (PAestrela Branco - 50%algod. 50%poliester)','OASM',now(),2,8,'aikido infantil mirim algodao kimono'),
('AikidoGI "Star" Infantil','branco','105.0','134.9','OlimpicStar (PAestrela Branco - 50%algod. 50%poliester)','OAS1',now(),10,40,'aikido infantil algodao kimono'),
('AikidoGI "Star" Adulto','branco','125.0','160.6','OlimpicStar (PAestrela Branco - 50%algod. 50%poliester)','OAS2',now(),42,48,'aikido adulto algodao kimono'),
('AikidoGI "Star" Adulto extra','branco','145.0','186.3','OlimpicStar (PAestrela Branco - 50%algod. 50%poliester)','OAS3',now(),50,56,'aikido adulto extra algodao kimono'),
('AikidoGI Trançado Mirim','branco','110.0','141.3','"Trançado XLVIII" Reforçado 100% algodão Branco','TAKM',now(),2,8,'aikido infantil mirim algodao kimono'),
('AikidoGI Trançado Infantil','branco','130.0','167.0','"Trançado XLVIII" Reforçado 100% algodão Branco','TAK1',now(),10,40,'aikido infantil algodao kimono'),
('AikidoGI Trançado Adulto','branco','160.0','205.5','"Trançado XLVIII" Reforçado 100% algodão Branco','TAK2',now(),42,48,'aikido adulto algodao kimono'),
('AikidoGI Trançado Adulto extra','branco','185.0','237.7','"Trançado XLVIII" Reforçado 100% algodão Branco','TAK3',now(),50,56,'aikido adulto extra algodao kimono'),
('AikidoGI Losango Mirim','branco','110.0','141.3','FIGHT - indicado para KATA -100% algodão','ALSM',now(),2,8,'aikido infantil mirim algodao kimono'),
('AikidoGI Losango Infantil','branco','135.0','173.4','FIGHT - indicado para KATA -100% algodão','ALS1',now(),10,40,'aikido infantil algodao kimono'),
('AikidoGI Losango Adulto','branco','160.0','205.5','FIGHT - indicado para KATA -100% algodão','ALS2',now(),42,48,'aikido adulto algodao kimono'),
('AikidoGI Losango Adulto extra','branco','190.0','244.1','FIGHT - indicado para KATA -100% algodão','ALS3',now(),50,56,'aikido adulto extra algodao kimono');


